spring:
  application:
    name: jpa
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 2000
# Global Page Config



logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug